# 请勿修改
config-version: 8

# 当玩家加入服务器时，如果有新的更新可供下载，通过'mmoitems.update-notify'权限节点通知玩家。更改时需要执行/reload。
update-notify: true

# 启用/禁用插件迭代整个玩家库存而不仅仅是玩家的盔甲和手持物品。此选项对于"Ornament"物品类型是必需的，但可能会导致卡顿和/或占用大量内存。
iterate-whole-inventory: false

# 当设置为true时，皮肤只能应用于物品一次。
locked-skins: true

# 从6.9.3开发构建版本开始，MMOItems同时支持多个RPG核心插件。但是，MMOItems需要一个特定的插件来钩住等级、职业等。
#
# 可用插件：
# - MMOCORE（等级、职业、法力、耐力）
# - HEROES（等级、职业、法力、耐力）
# - SKILLAPI或PROSKILLAPI（等级、职业、法力）
# - RPGPLAYERLEVELING（等级、法力、力量）
# - RACESANDCLASSES（等级、职业、法力）
# - BATTLELEVELS（等级）
# - MCMMO（力量等级）
# - MCRPG（力量等级）
# - SKILLS或SKILLSPRO（职业、等级、法力）
# - AURELIUM_SKILLS（力量等级、法力）
preferred-rpg-provider: MMOCORE

# 默认情况下，所有玩家库存将每10个刻度更新一次，对应每秒2次库存更新。
inventory-update-delay: 10

# 生成物品时，物品等级必须与玩家等级大致匹配，否则玩家无法使用物品/获得无用的物品。
#
# 物品等级始终在[playerLevel - spread，playerLevel + spread]区间内
item-level-spread: 2

# 当前存在一个客户端Minecraft问题，即左键单击时
fix-left-click-interact: false

# 当生成物品时，没有等级时使用的容量公式。
default-item-capacity:
    base: 3
    scale: 0
    spread: 0
    max-spread: 0

# 更改某些统计信息的默认值。这主要适用于非定向武器，如法杖、火枪等...
default:
    attack-speed: 0.67
    range: 16
    blunt-rating: 33
    recoil: 0.1

# 更改此选项时重新启动服务器
dropped-items:

    # 根据它们的等级发光物品
    tier-glow: true

    # 在掉落物品上显示物品名称
    hints: true

# 一些物品统计信息，如'Commands'或NBTTags，可能会被滥用以变得强大。
# 您可以为这些统计信息绑定特定权限以限制其编辑。
# 对于此选项有效的插件需要支持Vault。
# 相应的权限是"mmoitems.edit.op"。
op-item-stats:
    enabled: false
    stats:
        - COMMANDS
        - CUSTOM_NBT

item-upgrading:

    # 升级物品时的显示名称后缀。
    name-suffix: ' &8(&e+#lvl#&8)'

    # 是否在物品名称或物品描述中显示
    # 如果可以让玩家重命名物品，请禁用。
    # 如果设置为'false'，请记住在物品描述中包括
    # {upgrade_level}。
    display-in-name: true

    # 是否显示物品描述中更改了哪些统计信息。
    display-stat-changes: false
    stat-change-suffix: ' &8(<p>#stat#&8)'
    stat-change-positive: '&a'
    stat-change-negative: '&c'

stats-displaying:

    # 这将是数值统计信息的前缀，当它们不可取时更改其颜色。
    color-positive: ''
    color-negative: ''

    # 当在制作工作站中显示具有RNG的物品时，这是低
    # 和高范围之间的分隔符：攻击伤害+5⎓7.5
    range-dash: '⎓'

soulbound:

    # 当玩家尝试使用未绑定到自己的物品时，编辑损伤绑定。
    damage:
        base: 1
        per-lvl: 1

    # 是否在玩家死亡时保留绑定的物品。
    keep-on-death: true

    # 是否可以通过玩家删除灵魂绑定物品
    can-drop: true

# 启用、禁用并自定义武器效果。
# 武器效果取决于物品类型和设置类型。
item-ability:
    staff:
        enabled: true
        cooldown: 30
        power: 1
    gauntlet:
        enabled: true
        cooldown: 60
        power: 1
    blunt:
        aoe:
            enabled: true
            cooldown: 2
        stun:
            enabled: true
            chance: 5
            cooldown: 30
            power: 1
    slashing:
        enabled: true
        cooldown: 2
    piercing:
        enabled: true
        cooldown: 4

gem-sockets:

    # 如果要创建一个未着色的宝石插槽，即任何类型的宝石插槽，定义物品中需要输入的文本。
    uncolored: 'Uncolored'

custom-blocks:

    # 是否应按照生成模板在世界中生成自定义方块。
    enable-world-gen: false

    # 当使用丝网触发时，是否删除蘑菇方块掉落
    # 自定义块。
    # 强烈推荐用于使用
    # 自定义块的服务器，因为蘑菇方块可以破坏一切。
    replace-mushroom-drops: true

# 如果你的聊天管理插件与MMOItems的聊天输入功能发生冲突，请使用此选项。
# 这将弹出一个可以在其中输入文本的铁砧GUI，而不是使用聊天。
anvil-text-input: false

# 当设置为true时，如果物品被升级后，物品的规格（等级、职业要求）对玩家来说太高，则玩家不能升级物品。
item-upgrade-requirements-check: true

# 当玩家同时持有双手物品和另一物品时，他们无法使用武器/技能。
# 当切换关闭时，玩家仍然受到缓慢4的影响。
two-handed-item-restriction: true

# 你可以选择用什么字符来创建
# 物品技能冷却进度条。
cooldown-progress-bar-char: █

# 在动作栏上显示消息而不是在聊天中显示。
# 可以用来减少聊天垃圾邮件。
# 可能会干扰其他动作栏插件。
action-bar-display:
    ability-cooldown: true
    item-cooldown: true
    not-enough-mana: true
    not-enough-stamina: true
    two-handed: true
    cant-use-item: true
    mitigation: true
    item-break: false

recipes:

    # 启用MMOItems配方的原始配方书
    use-recipe-book: true

# "repair"防止玩家修复MMOItems。
# "smelt"防止玩家熔炼MMOItems。
# "enchant"禁用MMOItems的附魔。
# "craft"防止玩家将MMOItems用作材料。
# "arrow-shooting"防止玩家射击任何MMOItem箭。
disable-interactions:
    interact: false
    repair: false
    enchant: false
    smelt: false
    smith: false
    craft: false
    arrow-shooting: false

# 不能被能力/物品效果打破的方块类型
block-blacklist:
    - OBSIDIAN

# 允许/禁用使用物品/技能所需的权限。
# 功能权限节点：mmoitems.ability.ability-id
# 例如：- mmoitems.ability.fire-meteor
#      - mmoitems.ability.slow
#      - mmoitems.ability.cursed-fangs
#      等等。
permissions:
    abilities: false
    items: true

#
# 当物品统计信息具有一定范围的可能性时。
# attack-damage:
#    base: 10
#    spread: 1
#
# 使用spread，一个等级和一个随机数，我们
# 得到一个随机数（与spread非常相关）：1.7
#
# 如果additive-spread-formula为true，则将其添加到基数中：
#    结果：10 + 1.7 = 11.7的攻击伤害
#
# 如果additive-spread-formula为false，则将其乘以基数：
#    结果：10 * 1.7 = 17的攻击伤害
#
additive-spread-formula: false

# 禁用不能在基本的工作台中制作的非MMOItems。
# 如果列表为空，请添加[]。
disable-vanilla-recipes: []
# - DIAMOND_PICKAXE
# - IRON_BLOCK

# 物品修订系统的选项
item-revision:

    # 取下宝石时，按照它们放入物品时的统计信息捡起它们。
    # 禁用此选项将强制它们被重新生成。
    regenerate-gems-when-unsocketed: false

    # 保留层次的传统选项，将优先级
    # 如果未指定，则旁边的keep-标志。
    keep-tiers: true

    # 如果升级物品的新版本不保留其宝石，则将这些宝石返还给玩家，以免它们永远丢失。
    drop-extra-gems: true

    # 当保留Lore数据时，只有以此开头的Lore实际上才会被保留。
    kept-lore-prefix: '&7'

    # 当物品被升级到最新版本时，是否应该保留特定统计信息
    keep-data:

        # 物品的名称，通常是通过铁砧重命名的
        display-name: true

        # 玩家对物品施加的附魔
        enchantments: true

        # 施加到物品的灵魂绑定
        soulbound: true

        # 物品上的宝石
        gems: true

        # 物品的升级级别
        upgrades: true

        # 物品的特定Lore行...
        # 警告，这会阻止Lore中的统计信息在视觉上更新！
        lore: false

        # 可能是由外部插件放入的数据。
        exsh: true

        # 由RNG处理的统计信息将被重新掷骰子
        reroll: false

        # 物品的修改器 ~ 锐利、轻巧、沉重、奥术
        modifications: true

        # MMOItems应用的皮肤
        skins: true

        # 物品的层次
        tier: true

        # 第三方插件兼容性
        advanced-enchantments: true

    # 当物品内的宝石被更新到最新版本时，是否应该保留特定统计信息
    keep-gem-data:

        # 物品的名称，通常通过铁砧更名
        display-name: true

        # 玩家添加的物品附魔
        enchantments: true

        # 物品的特定属性描述...
        # 警告，这将阻止属性在描述中更新显示！
        lore: false

        # 通过RNG处理的属性将被重新生成
        reroll: false

phat-loots:
    display-name: false
    enchantments: false
    soulbound: false
    gems: true
    upgrades: false
    lore: false
    exsh: false
    tier: true
    skins: false
    reroll: true
    modifications: false
    advanced-enchantments: false

# 这些物品在PhatLoots中完全不会更新，以便与检查具体NBT的任务插件兼容
disable-phat-loot:
    - MANGO
    - STEEL_HELMET

# 在这里，你可以禁用物品在找到更高版本ID时更新时的个别事件
disable-on:
    pickup: false
    craft: true # 'true' 推荐
    click: false
    join: false

# 偏移量是X和Y坐标上的移动距离
# 高度是Y轴速度坐标。Lootsplosions
# 仅在MythicMobs怪物触发时发生。
# 更改时需要服务器重新加载。
lootsplosion:
    enabled: true
    color: true
    offset: .2
    height: .6

# 当升级遇到宝石时，必须决定是否
# 宝石的统计信息也会增加。
gem-upgrade-default: 'NEVER'

# 此选项允许您禁用使用已从配置中删除的MMOItems的能力。
disable-removed-items: true